preload=/home/naxecode/Pictures/wallpapers/everforest_dark.jpg
preload=/home/naxecode/Pictures/wallpapers/everforest_light.jpg
wallpaper=,/home/naxecode/Pictures/wallpapers/everforest_light.jpg
splash=false
ipc=on
